# Generated by Django 3.0.7 on 2020-06-14 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('workingTime', models.PositiveIntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('startingDate', models.DateTimeField()),
                ('endingDate', models.DateTimeField()),
                ('workingDays', models.PositiveIntegerField(default=21)),
            ],
            options={
                'ordering': ['startingDate'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to='worklog.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthWorkingTime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklog.Employee')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklog.Month')),
            ],
            options={
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHoursEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklog.Activity')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklog.Employee')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklog.EmployeeMonth')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklog.Project')),
            ],
            options={
                'ordering': ['startDate'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ManyToManyField(to='worklog.Position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='project',
            field=models.ManyToManyField(to='worklog.Project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklog.Position'),
        ),
    ]
