# Generated by Django 3.0.7 on 2020-06-13 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('workingTime', models.PositiveIntegerField(default=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('startingDate', models.DateTimeField()),
                ('endingDate', models.DateTimeField()),
                ('workingDays', models.PositiveIntegerField(default=21)),
            ],
            options={
                'ordering': ['startingDate'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkLog.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthWorkingTime', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkLog.Employee')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkLog.Month')),
            ],
            options={
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHoursEnrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
                ('length', models.IntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkLog.Activity')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkLog.Employee')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkLog.EmployeeMonth')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkLog.Project')),
            ],
            options={
                'ordering': ['startDate'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkLog.Position'),
        ),
    ]
