# Generated by Django 3.0.7 on 2020-06-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkLog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ManyToManyField(to='WorkLog.Position'),
        ),
    ]
