# Generated by Django 3.0.7 on 2020-06-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkLog', '0002_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehoursenrolment',
            name='length',
            field=models.FloatField(),
        ),
    ]
