# Generated by Django 3.0.7 on 2020-06-14 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkLog', '0003_auto_20200614_0046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeHoursEnrolment',
            new_name='EmployeeHoursEnrollment',
        ),
    ]
