# Generated by Django 3.0.7 on 2020-06-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkLog', '0004_auto_20200614_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemonth',
            name='monthWorkingTime',
            field=models.FloatField(default=0),
        ),
    ]
