# Generated by Django 3.0.7 on 2020-06-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkLog', '0005_auto_20200614_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehoursenrollment',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employeemonth',
            name='monthWorkingTime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
